language: php

php:
  - 5.2
  - 5.3
  - 5.4

before_script:
  - cd tests
  - ./travis/mysql-setup.sh
  - ./travis/postgresql-setup.sh
  - ./travis/memcache-setup.sh

script: phpunit --colors --coverage-text --exclude-group mssql framework
