language: php

php:
  - 5.2
  - 5.3
  - 5.4

branches:
  only:
    - fix-travis-ci-failing

before_script:
  - cd tests
  - mysql -u root -e 'CREATE SCHEMA `yii` CHARACTER SET utf8 COLLATE utf8_general_ci; GRANT ALL ON `yii`.* TO test@localhost IDENTIFIED BY "test"; FLUSH PRIVILEGES;'
  - mysql -u root -D yii < framework/db/data/mysql.sql
  - pecl install -s -f -l memcache
  - echo "extension=memcache.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script: phpunit --verbose --coverage-html reports framework
